Simplified Contributing guides
apigee/devrel pull request #208
Opened 2021-03-15 11:29 UTC by laughingbiscuit

As discussed with @seymen and @danistrebel - a set of simplified Contributing steps and separation of pipeline details.

- [ ] I have run all the tests locally and they all pass.
- [ ] I have followed the relevant style guide for my changes.

2021-03-15 13:39 UTC, danistrebel reviewed
Minor comments.

2021-03-15 13:39 UTC, danistrebel commented on CONTRIBUTING.md
> +- Put a new line in the [CODEOWNERS](./CODEOWNERS) file to declare [ownership](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)
Maybe indicate that this only applies to new solutions and not small fixes etc.

2021-03-15 13:39 UTC, danistrebel commented on PIPELINES.md
> +- is run whenever a Pull Request changes that projects
trivial `project`

2021-03-15 13:39 UTC, danistrebel commented on PIPELINES.md
> + the subdirectory `./generated/docs`, after which it will be deployed to GitHub
after which => from where?

2021-03-15 13:39 UTC, danistrebel commented on CONTRIBUTING.md
> +- Put the [Apache](https://opensource.google/docs/releasing/preparing/#Apache-header)
trivial `Apache` => `Apache 2.0`

2021-03-17 17:39 UTC, laughingbiscuit commented
/gcbrun

2021-03-18 09:36 UTC, seymen requested changes

2021-03-18 09:36 UTC, seymen commented on PIPELINES.md
> + review, to reduce the risk of exposing secrets
let's not reveal too much here. How about `can be triggered manually at any time by ??`

2021-03-18 09:45 UTC, seymen approved these changes

2021-03-18 09:51 UTC, laughingbiscuit commented
/gcbrun

2021-03-18 11:32 UTC, merged