Code review cleanup
apigee/devrel pull request #600
Opened 2022-08-31 19:46 UTC by ganadurai

## Description
What's changed, or what was fixed?

Addressed the fixes for https://github.com/apigee/devrel/issues/599 , except point #3, waiting for further comments on it

## Housekeeping
(please check all that apply [x], do not edit the text)
- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

## Full Repo Validation Required
(please check all that apply [x], do not edit the text)
- [ ] PR requires full pipeline run (Run for changes only by default).

**CC:** @apigee-devrel-reviewers

2022-09-01 10:27 UTC, danistrebel requested changes

2022-09-01 10:27 UTC, danistrebel commented on tools/apigee-envoy-quickstart/README.md
> +    git clone https://github.com/apigee/devrel/archive/refs/heads/main.zip
This doesn't work

2022-09-01 14:39 UTC, ganadurai commented on tools/apigee-envoy-quickstart/README.md
> +    git clone https://github.com/apigee/devrel/archive/refs/heads/main.zip
duh.... stupid mistake. .. will fix it.

2022-09-02 13:18 UTC, danistrebel approved these changes
Thanks @ganadurai

2022-09-02 13:18 UTC, danistrebel commented
/gcbrun

2022-09-02 13:29 UTC, merged